### ISSUE TITLE
GPIO32 conflict / BL is controlled by pmux

### ISSUE THREAD

**Issue by jci-zimm** [nopnop2002/esp-idf-m5stickC-Plus#3]
Hey, thanks for the library! 

Just a note, in https://github.com/nopnop2002/esp-idf-m5stickC-Plus/blob/main/main/main.c#L31 you have 
```c
#define CONFIG_BL_GPIO	  32
```
which ends up getting passed into the screen lib implied as a GPIO that controls the backlight. There actually isn't a GPIO, to my knowledge, that controls the LCD backlight. Instead it is controlled by the pmux / axp192. This GPIO32 usage causes issues if one is attempting to use the grove port on the M5stickcplus

**Comment by nopnop2002** [comment]
Thank you for reporting.

As you say, the backlight is controlled by axp192.

GPIO for backlight has been abolished in the latest version.
